version: '3.3'

services:
  app1:
    restart: on-failure
    environment:
      - NAME_APP=app1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server_files:/var/prac5

  app2:
    restart: on-failure
    environment:
      - NAME_APP=app2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./server_files:/var/prac5

#  app3:
#    restart: on-failure
#    environment:
#      - NAME_APP=app3
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./server_files:/var/prac5
#
#  app4:
#    restart: on-failure
#    environment:
#      - NAME_APP=app4
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./server_files:/var/prac5

  proxy:
    image: nginx:1.11
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
